# Generated by Django 4.2.1 on 2023-06-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='images/')),
                ('color', models.CharField(choices=[('P', '紫色'), ('R', '紅色'), ('Y', '黃色'), ('B', '藍色'), ('G', '綠色')], default='P', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unfinished', '未完成'), ('finished', '完成')], default='unfinished', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('knit', '針織衫'), ('shirt', '襯衫'), ('sweat', '大學T'), ('t_shirt', 'T恤'), ('tank_top', '吊帶背心'), ('vest', '背心')], max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(upload_to='images/')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('color', models.CharField(choices=[('black', '黑色'), ('blue', '藍色'), ('yellow', '黃色'), ('pink', '粉色'), ('brown', '深褐色'), ('beige', '淺棕色'), ('purple', '紫色'), ('green', '綠色'), ('white', '白色')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('shoppingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppingcart')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ManyToManyField(through='shopping.ShoppingCart_Product', to='shopping.product'),
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('shipping_date', models.DateField()),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('shipping_address', models.CharField(max_length=128)),
                ('shipping_status', models.CharField(choices=[('undelivered', '尚未發貨'), ('delivering', '送貨中'), ('delivered', '已送達')], default='undelivered', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('productPhoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.productphoto')),
            ],
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product',
            field=models.ManyToManyField(through='shopping.ProductPhoto_Product', to='shopping.product'),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('visa', 'Visa'), ('transfer', '匯款'), ('COD', '貨到付款')], max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款')], default='unpaid', max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='shopping.Order_Product', to='shopping.product'),
        ),
        migrations.CreateModel(
            name='FollowList_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.followlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.AddField(
            model_name='followlist',
            name='product',
            field=models.ManyToManyField(through='shopping.FollowList_Product', to='shopping.product'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('content', models.TextField(max_length=255)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.customer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
    ]
