# Generated by Django 4.2.1 on 2023-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.URLField(),
        ),
    ]
